object Form1: TForm1
  Left = 0
  Top = 0
  Caption = 'Form1'
  ClientHeight = 202
  ClientWidth = 371
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object BtnPrint: TButton
    Left = 0
    Top = 0
    Width = 371
    Height = 202
    Align = alClient
    Caption = 'Print'
    TabOrder = 0
    OnClick = BtnPrintClick
    ExplicitLeft = 256
    ExplicitTop = 144
    ExplicitWidth = 75
    ExplicitHeight = 25
  end
end
